languageCode = 'en-in'
title = 'Core dump blog'
copyright = '© Ananth Bhaskararaman'
paginate = 3
enableGitInfo = true

[module]
[[module.imports]]
path = 'github.com/ananthb/jughead'

[params]
mode='auto' # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = 'Stream of consciousness (core dumped) in UTF-8'
attribution = true

[params.utterances]
repo = 'ananthb/coredump.blog'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 4
