defaultContentLanguage = 'en'
languageCode = 'en-in'
title = '/dev/human'
copyright = 'Â© Ananth Bhaskararaman'
enableGitInfo = true
enableRobotsTXT = true

[module]
[[module.imports]]
path = 'github.com/ananthb/jughead'

[params]
description = """Ananth blogs about computers, distributed systemd, programming languages,
and other things that interest him."""
subtitle = 'crw-rw-rw- 1 ananth ananth 5, 0 May  19 22:33 /dev/human'
attribution = true
github_repo = 'ananthb/devhuman.net'
utterances = 'ananthb/devhuman.net'

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/ananthb'
[[params.social]]
name = 'LinkedIn'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/ananth-bhaskararaman-2b4227316'

[taxonomies]
tag = 'tags'

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2
