defaultContentLanguage = 'en'
languageCode = 'en-in'
title = 'Core Dump Blog'
copyright = '© Ananth Bhaskararaman'
paginate = 3
enableGitInfo = true

[module]
[[module.imports]]
path = 'github.com/ananthb/jughead'

[params]
mode='auto' # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = 'Tales from the machine'
attribution = true
github_repo = 'ananthb/coredump.blog'
utterances = 'ananthb/coredump.blog'

[taxonomies]
tag = 'tags'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
