defaultContentLanguage = 'en'
languageCode = 'en-in'
title = 'Core Dump Blog'
copyright = '© Ananth Bhaskararaman'
paginate = 3
enableGitInfo = true
enableRobotsTXT = true

[module]
[[module.imports]]
path = 'github.com/ananthb/jughead'

[params]
description = """Core Dump Blog by Ananth tells you real hard-hitting stories
of machines, their dreams, and their human friends."""
mode='auto'   # color-mode → light,dark,toggle or auto
useCDN=false  # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = 'Tales from the machine'
attribution = true
github_repo = 'ananthb/coredump.blog'
utterances = 'ananthb/coredump.blog'

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/ananthb'
[[params.social]]
name = 'LinkedIn'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/ananth-bhaskararaman-2b4227316'

[taxonomies]
tag = 'tags'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
